global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'otel-lab'
    environment: 'development'

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape OpenTelemetry Collector metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
        labels:
          service: 'otel-collector'

  # NOTE: otel-collector-prometheus-exporter job removed
  # Collector no longer exports Prometheus metrics (only traces/logs).
  # Flask backend metrics are now the sole source via prometheus_client.

  # Scrape Flask backend metrics
  - job_name: 'flask-backend'
    static_configs:
      - targets: ['backend:5000']
        labels:
          service: 'flask-backend'

  # Scrape Tempo metrics
  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']
        labels:
          service: 'tempo'

  # Scrape Loki metrics
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
        labels:
          service: 'loki'

  # Scrape Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
        labels:
          service: 'grafana'
